// proto/validator.proto
syntax = "proto3";

package validator;

import "google/protobuf/descriptor.proto";

// 数值类型校验规则
// 示例：int32类型规则
message Int32Rule {
  oneof lt_rule { int32 lt = 1; }    // 小于
  oneof lte_rule { int32 lte = 2; }  // 小于等于
  oneof gt_rule { int32 gt = 3; }    // 大于
  oneof gte_rule { int32 gte = 4; }  // 大于等于
  repeated int32 in = 5;             // 白名单
  repeated int32 not_in = 6;         // 黑名单
}

message Int64Rule {
    oneof lt_rule { int64 lt = 1; }
    oneof lte_rule { int64 lte = 2; }
    oneof gt_rule { int64 gt = 3; }
    oneof gte_rule { int64 gte = 4; }
    repeated int64 in = 5;
    repeated int64 not_in = 6;
}

message UInt32Rule {
    oneof lt_rule { uint32 lt = 1; }
    oneof lte_rule { uint32 lte = 2; }
    oneof gt_rule { uint32 gt = 3; }
    oneof gte_rule { uint32 gte = 4; }
    repeated uint32 in = 5;
    repeated uint32 not_in = 6;
}

message UInt64Rule {
    oneof lt_rule { uint64 lt = 1; }
    oneof lte_rule { uint64 lte = 2; }
    oneof gt_rule { uint64 gt = 3; }
    oneof gte_rule { uint64 gte = 4; }
    repeated uint64 in = 5;
    repeated uint64 not_in = 6;
}

message FloatRule {
    oneof lt_rule { float lt = 1; }
    oneof lte_rule { float lte = 2; }
    oneof gt_rule { float gt = 3; }
    oneof gte_rule { float gte = 4; }
    repeated float in = 5;
    repeated float not_in = 6;
}

message DoubleRule {
    oneof lt_rule { double lt = 1; }
    oneof lte_rule { double lte = 2; }
    oneof gt_rule { double gt = 3; }
    oneof gte_rule { double gte = 4; }
    repeated double in = 5;
    repeated double not_in = 6;
}

// 字符串类型校验规则
message StringRule {
    bool not_empty = 1;
    oneof min_len_rule { uint32 min_len = 2; }
    oneof max_len_rule { uint32 max_len = 3; }
    string regex_pattern = 4;
}

// 枚举类型校验规则
message EnumRule {
    repeated int32 in = 1;
}

// 数组类型校验规则
message ArrayRule {
    bool not_empty = 1;
    oneof min_len_rule { uint32 min_len = 2; }
    oneof max_len_rule { uint32 max_len = 3; }
}

// 统一的校验规则
message ValidateRules {
    oneof rule {
        Int32Rule int32 = 1;
        Int64Rule int64 = 2;
        UInt32Rule uint32 = 3;
        UInt64Rule uint64 = 4;
        FloatRule float = 5;
        DoubleRule double = 6;
        StringRule string = 7;
        EnumRule enum = 8;
        ArrayRule array = 9;
    }
}

// 扩展字段选项
extend google.protobuf.FieldOptions {
    ValidateRules Rule = 10000;
}